[package]
name = "cgol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cgol"
path = "src/main.rs"

[dependencies]
gtk4 = "0.4.7"
itertools = "0.10.3"
rand = "0.8.5"
